
```{r}
library(ggplot2)
library(readxl)
library(tidyverse); theme_set(theme_bw() + theme(text = element_text(size = 18)))
library(car)
library(rstatix)
library(GGally)
library(dplyr)
library(knitr)
library(corrplot)
library(MASS)
library(broom)
library(caret)

setwd("E:/R")
carotene <- read_excel("data/carotene.xlsx")
data<-carotene
data$smokstat <- factor(data$smokstat, labels = c("Never", "Former", "Current"))
data$smokstat <- relevel(data$smokstat, ref = "Never")
data$sex <- factor(data$sex, labels = c("Male", "Female"))
data$sex <- relevel(data$sex, ref = "Female")
data$vituse <- factor(data$vituse, labels = c("Often", "Rarely", "No"))
data$vituse <- relevel(data$vituse, ref = "Often")
```


```{r}
data |> mutate(
plasma_category = cut(carotene$betaplasma, breaks = c(0, 50, 225, 1600), include.lowest = TRUE),
plasma_c = factor(plasma_category,
levels = c("[0,50]", "(50,225]", "(225,1.6e+03]"),
labels = c(0, 1, 2))) -> data
```


```{r}
summary(data)
```


```{r}
model.null <- polr(plasma_category ~ 1, data = data)
sum.null <- summary(model.null)
sum.null

```


```{r}
model.full_calories <- polr(plasma_category ~ bmi + age + calories + fat + cholesterol + fiber + alcohol + betadiet + 
    smokstat + sex + vituse, data = data)
sum.full <- summary(model.full_calories)
sum.full

vif(model.full_calories)
```


```{r}
#so we still need to remove calories
model.full<- polr(plasma_category ~ bmi + age + fat + cholesterol + fiber + alcohol + betadiet + 
    smokstat + sex + vituse, data = data)
sum.full <- summary(model.full)
sum.full

vif(model.full)
```
```{r}
model_lm.intereaction <- lm(betaplasma ~ (bmi + age + fat + cholesterol + fiber + alcohol + betadiet + 
    smokstat + sex + vituse)^2, data = data)

summary(model_lm.intereaction)
``` 


```{r}
#variable selection, we can not form a model with full intereaction due to sample deficiencies in some intereactions, so we did a linear model to find some intereactions that are significant to betaplasma.
model.intereaction <- polr(plasma_category ~ bmi + age + fat + cholesterol + fiber + alcohol + betadiet + 
    smokstat + sex + vituse + age:betadiet + fiber:vituse + alcohol:vituse + smokstat:vituse, data = data)
```


```{r}
# backward
backward_model <- step(
  model.intereaction,
  direction = "backward",
  scope = list(lower = ~1, upper = formula(model.intereaction)),
  k = log(nrow(data))
)
```


```{r}
# forward
forward_model <- step(
  model.null,
  direction = "forward",
  scope = list(lower = ~1, upper = formula(model.intereaction)),
  k = log(nrow(data))
)
```
```{r}
#backstep
backstep_model <- step(
  backward_model,
  direction = "both",
  scope = list(lower = ~1, upper = formula(model.intereaction)),
  k = log(nrow(data))
)

```


```{r}
#forstep
forstep_model <- step(
  forward_model,
  direction = "both",
  scope = list(lower = ~1, upper = formula(model.intereaction)),
  k = log(nrow(data))
)

```
All these selections lead to one model.

```{r}
new_data <- data
new_data$vituse <- factor(
  ifelse(new_data$vituse %in% c("Often", "Rarely"), "Yes", "No"),
  levels = c("Yes", "No")
)

reduced_model <- polr(plasma_category ~ vituse + betadiet + bmi +cholesterol + age,
                      data = new_data)
```
```{r}
#model comparison
library(pscl)
library(performance)
library(DescTools)

# McFadden R2
get_model_metrics <- function(model) {
  data.frame(
    adj_McFadden = r2_mcfadden(model)$R2_adjusted,
    McFadden_R2 = pR2(model)["McFadden"],
    AIC = AIC(model),
    BIC = BIC(model)
  )
}

# all models
metrics_table <- rbind(
  "Full Model" = get_model_metrics(model.intereaction),
  "Stepwise" = get_model_metrics(forstep_model),
  "Reduced" = get_model_metrics(reduced_model)
)
kable(metrics_table, caption = "Comparison")
```

```{r}
cbind(beta = reduced_model$coefficients, 
      expbeta = exp(reduced_model$coefficients),
      exp(confint(reduced_model)))
model.final <- reduced_model
```
```{r}
cbind(zeta = reduced_model$zeta, 
      expzeta = exp(reduced_model$zeta))
```

```{r}
D_0 <- model.null$deviance
df_0 <- model.null$edf

info <- cbind(aic = AIC(model.null, model.final),
              bic = BIC(model.null, model.final),
              R2D = c(1 - 1, 
                      1 - model.final$deviance/D_0),
              R2D.adj = c(1 - 1, 
                          1 - (model.final$deviance + model.final$edf - df_0)/D_0))
round(info, digits = 3)
```
```{r}
anova(model.null, model.final)
```

```{r}
new_data |> mutate(yhat = predict(model.final)) -> pred.final

confusionMatrix(data = pred.final$yhat,
                reference = pred.final$plasma_category)
```


```{r}
#multinomial logistic regression
library(nnet)
library(caret)
```

```{r}
data |> count(plasma_category)
```
```{r}
data_multi <- data
data_multi |> mutate(plasma_category = relevel(plasma_category, ref = "(50,225]")) ->
  data_multi
```

```{r}
model.null_multi <- multinom(plasma_category ~ 1, data = data_multi)
sum_multi.null <- summary(model.null_multi)
sum_multi.null
```

```{r}
model.full_multi <- multinom(plasma_category ~ bmi + age + fat + cholesterol + fiber + alcohol + betadiet + smokstat + sex + vituse + age:betadiet + fiber:vituse + alcohol:vituse + smokstat:vituse, data = data_multi)
sum_multi.full <- summary(model.full_multi)
sum_multi.full

```

```{r}
# backward selection
model.back_multi <- step(
  model.full_multi,
  direction = "backward",
  scope = list(lower = ~1, upper = formula(model.full_multi)),
  k = log(nrow(data_multi))
)
summary(model.back_multi)
```
```{r}
# forward selection
model.for_multi <- step(
  model.null_multi,
  direction = "forward",
  scope = list(lower = ~1, upper = formula(model.full_multi)),
  k = log(nrow(data_multi))
)
summary(model.for_multi)
```

```{r}
#backstep 
model.backstep_multi <- step(
  model.back_multi,
  direction = "both",
  scope = list(lower = ~1, upper = formula(model.full_multi)),
  k = log(nrow(data_multi))
)
summary(model.backstep_multi)
```

```{r}
#forstep 
model.forstep_multi <- step(
  model.for_multi,
  direction = "both",
  scope = list(lower = ~1, upper = formula(model.full_multi)),
  k = log(nrow(data_multi))
)
summary(model.forstep_multi)
```
```{r}
new_data_multi <- data_multi
new_data_multi$vituse <- factor(
  ifelse(new_data_multi$vituse %in% c("Often", "Rarely"), "Yes", "No"),
  levels = c("Yes", "No")
)
 model.red_multi <- multinom(plasma_category ~ bmi + age + cholesterol + 
    alcohol + betadiet + smokstat + vituse + alcohol:vituse + 
    smokstat:vituse, data = new_data_multi)
sum.red_multi <- summary(model.red_multi)
sum.red_multi
```

```{r}
model.final_multi<-model.red_multi
sum.final_multi<-sum.red_multi

beta <- sum.final_multi$coefficients
se.beta <- sum.final_multi$standard.errors
z.value <- beta/se.beta
P.value <- pnorm(abs(z.value), lower.tail = FALSE)
ci_beta <- confint(model.final_multi)
OR <- exp(beta)
ci_OR <- exp(ci_beta)
beta
ci_OR
```

```{r}
beta_0_50 <- cbind(
  beta = round(beta["[0,50]", ], digits = 2),
  P.value = round(P.value["[0,50]", ], digits = 3),
  OR = round(OR["[0,50]", ], digits = 2),
  round(ci_OR[, , "[0,50]"], digits = 2))

beta_0_50
```

```{r}
beta_225_1600 <- cbind(
  beta = round(beta["(225,1.6e+03]", ], digits = 2),
  P.value = round(P.value["(225,1.6e+03]", ], digits = 3),
  OR = round(OR["(225,1.6e+03]", ], digits = 2),
  round(ci_OR[, , "(225,1.6e+03]"], digits = 2))

beta_225_1600
```

```{r}
info_multi <- cbind(aic = AIC(model.null_multi, model.final_multi, model.full_multi),
              bic = BIC(model.null_multi, model.final_multi, model.full_multi))
D_0 <- model.null_multi$deviance
df_0 <- model.null_multi$edf
info_multi$r2 <- round(c(
  1 - model.null_multi$deviance/D_0,
  1 - model.final_multi$deviance/D_0,
  1 - model.full_multi$deviance/D_0), digits = 3)

info_multi$r2.adj <- round(c(
  1 - (model.null_multi$deviance + (model.null_multi$edf - df_0))/D_0,
  1 - (model.final_multi$deviance + (model.final_multi$edf - df_0))/D_0,
  1 - (model.full_multi$deviance + (model.full_multi$edf - df_0))/D_0),
  digits = 3)

info_multi

```

```{r}
new_data_multi |>
  mutate(
    p = predict(model.final_multi, type = "probs"),
    yhat = predict(model.final_multi)) -> pred.final_multi

confusionMatrix(data = pred.final_multi$yhat, 
                reference = pred.final_multi$plasma_category)
```

























```




